### ISSUE TITLE
CORS

### ISSUE THREAD

**Issue by rndprdn** [dscesaunggul/perpustakaan#1]
saya mau nanya perihal cors, yang saya tau cors itu adalah sebuah permission untuk melakukan http request.. saya sedang belajar restAPI dan muncul masalah pada CORS, cors memblock request apinya. bagaimana cara mengatasi permasalahan pada cors tsb..

**Comment by azharprabudi** [comment]
Untuk mengatasi permasalah cors di rest api harus ditambahin allow origin bang pada proses preflight request (options) terhadap domain tertentu atau semua domain bang, biasanya cors ini ditempelin ke middleware dri rest api bang

**Comment by zalhamami** [comment]
Iyaa bener tinggal buat middleware aja. atau kalo gamau ribet ada tuh library buat cors (contoh: [laravel-cors](https://github.com/barryvdh/laravel-cors), [flask-cors](https://flask-cors.readthedocs.io), [django-cors-headers](https://github.com/adamchainz/django-cors-headers), dll). Tergantung pake framework apa, tinggal dicari aja terus pasang deh

**Comment by azharprabudi** [comment]
Ya paling enak si pake library, tp mesti tau dulu juga apa yg terjadi dibelakang cors itu kaya gimana. Karna kadang, hal hal yg sifatnya teoritis kaya gni, suka dipertanyakan ketika proses interview kerja

**Comment by rndprdn** [comment]
Yang bikin bingung, saya coba request di reactjs menggunakan axios dan fetch kena block, temen saya pakai react native gak kena😂

**Comment by azharprabudi** [comment]
Ini cuma berlaku di web doang om, karena diweb itu ada proses kaya handshaking antara client sama server, kalau di inspect element nnti bakal keliatan ada metode option namanya

**Comment by rndprdn** [comment]
Ohh, kalau di setting dari client bisa gak bang cors itu, saya udh baca", tambahain parameter di headernya, Tetep kena

**Comment by azharprabudi** [comment]
Jangan di client bang, itu msti ditempelin di middleware sisi server bang, untuk ngizinin segala request dri beda domain diizinin

**Comment by rndprdn** [comment]
Okay, thank you abang"😁
